### ISSUE TITLE
error

### ISSUE THREAD

**Issue by RaliVault** [g0ldyy/NameIt#6]
Hello. Thank you for the wonderful code.
An error occurred when running this code self.espColor = pm.new_color_float(self.config["esp"]["color"]["r"], self.config["esp"]["color" ]["g"], self.config["esp"]["color"]["b"], self.config["esp"]["color"]["a"])module' is , pyMeow' has no attribute 'new_color_float' happened.
What should I do?

**Comment by g0ldyy** [comment]
You need to build latest pymeow source by yourself using nimble and put the .pyd compiled file in same folder as the script.

**Comment by RaliVault** [comment]
I see. thank you.
Also, how can I remove or increase functionality from this code?
I'm thinking of creating Glow

**Comment by g0ldyy** [comment]
well simply modify the code (each feature is in a different thread) and feel free to do a pull request :)

**Comment by RaliVault** [comment]
thx so much!
I'll leave this issue alone to listen to other errors :)

**Comment by RaliVault** [comment]
uhh

Which version of pymeow?

**Comment by ImInTheICU** [comment]
You'll need to compile the newest version of PM.
In the README there is instructions on how to install Nimble and build PyMeow.
If you don't want to go threw the hassle there's a prebuilt one here. (I've zipped it because Github won't allow me to upload PyMeow.pyd)

[pyMeow.zip](https://github.com/g0ldyy/NameIt/files/14155368/pyMeow.zip)

**Comment by RaliVault** [comment]
oh thanks,
by the way,you know need updating?

**Comment by g0ldyy** [comment]
it's updating offsets automatically.
